import { createDefaultCheckpoints, getStageCountForMatchFormat } from "../settings";
import type { LineupSlot, MatchFormat, SettingsState } from "../types";


export const lineupSlots: LineupSlot[] = [
  { id: "damage-1", role: "damage", label: "输出" },
  { id: "damage-2", role: "damage", label: "输出" },
  { id: "tank", role: "tank", label: "坦克" },
  { id: "support-1", role: "support", label: "辅助" },
  { id: "support-2", role: "support", label: "辅助" },
];

const defaultMatchFormat: MatchFormat = "ft3";

export const defaultSettings: SettingsState = {
  matchName: "OW Ban Pick Invitational",
  teams: { left: "蓝色方", right: "红色方" },
  matchFormat: defaultMatchFormat,
  startWithDefaultConfig: false,
  teamsCanEditOwnName: false,
  stageCount: getStageCountForMatchFormat(defaultMatchFormat),
  checkpoints: createDefaultCheckpoints(getStageCountForMatchFormat(defaultMatchFormat)),
  stageLimits: {
    preStartRestSeconds: 30,
    interactiveRandomSeconds: 30,
    mapSelectSeconds: 45,
    sidePickSeconds: 30,
    playerSelectSeconds: 60,
    firstBanChoiceSeconds: 25,
    firstBanActionSeconds: 25,
    secondBanActionSeconds: 25,
    scoreConfirmSeconds: 30,
    postMatchRestSeconds: 120,
    timeoutExtensionSeconds: 30,
  },
  mapPool: {
    Control: ["Lijiang Tower", "Ilios", "Oasis", "Antarctic Peninsula"],
    Escort: ["Circuit Royal", "Dorado", "Rialto"],
    Hybrid: ["Hollywood", "King's Row", "Numbani"],
    Push: ["Colosseo", "New Queen Street", "Runasapi"],
    Flashpoint: ["Suravasa", "New Junk City"],
  },
  heroPool: { tank: [], damage: [], support: [] },
  mapSelectionMode: "first_mode_then_unique_mode",
  firstMapMode: "Control",
  modeOrder: ["Control", "Push", "Hybrid", "Escort", "Flashpoint", "Control", "Push"],
  fixedMapOrderText: "Lijiang Tower\nKing's Row\nDorado\nColosseo\nSuravasa\nIlios\nRunasapi",
  fixedFirstMapEnabled: false,
  fixedFirstMapName: "Antarctic Peninsula",
  initialPriorityPolicy: "interactive_random",
  subsequentPriorityPolicy: "previous_loser",
  mapPickTimeoutPolicy: "retry_after_delay",
  interactiveRandomMissingInputPolicy: "use_zero",
  firstMapSideChoiceEnabled: false,
  sideChooserRelation: "priority",
  sideTimeoutPolicy: "chooser_blue_defense",
  firstMapPickerPolicy: "random",
  mapPickerPolicy: "loser_choose",
  mapTimeoutPolicy: "warn_extend_30",
  symmetricSideChoiceEnabled: false,
  firstSideChoicePolicy: "map_picker",
  subsequentSideChoicePolicy: "previous_loser",
  rosterMode: "free_input",
  presetRosterText: "蓝色方: A1,A2,A3,A4,A5\n红色方: B1,B2,B3,B4,B5",
  banEnabled: true,
  banAdvantageRelation: "priority",
  banOrderPolicy: "advantage_chooses",
  banOrderTimeoutPolicy: "advantage_first",
  banActionTimeoutPolicy: "retry_after_delay",
  lineupTimeoutPolicy: "retry_after_delay",
  firstBanPolicy: "allow_loser_choose",
  openingSidePolicy: "random",
  banTimeoutPolicy: "warn_extend_30",
  scoreReportMode: "team_submit_opponent_confirm",
  scoreConfirmationTimeoutPolicy: "auto_confirm",
  globalPauseEnabled: true,
  teamPauseEnabled: true,
  teamPauseMaxCountPerMap: null,
  teamPauseMaxSingleSeconds: null,
  teamPauseMaxTotalSeconds: null,
  rollbackEnabled: true,
  allowRollbackAfterCompletion: false,
};
